const list = {
  products: [
    {
      name: "Nokia Lumia",
      id: 1,
      rating: 4,
      nor: 10,
      price: 8000,
      noofstock: 19,
      brand: "nokia",
      img: "/img/nokia.jpg",
      description: "strong phone",
    },
    {
      name: "Sony Xperia",
      id: 2,
      nor: 10,
      rating: 5,
      noofstock: 14,
      price: 15000,
      brand: "sony",
      img: "/img/sony.jpg",
      description: "camera phone",
    },
    {
      name: "Samsung Galaxy",
      id: 3,
      rating: 4,
      nor: 10,
      price: 10000,
      noofstock: 18,
      brand: "Samsung",
      img: "/img/samsung.jpg",
      description: "performace phone",
    },
    {
      name: "Apple 11 Pro",
      id: 4,
      rating: 4,
      nor: 10,
      price: 70000,
      noofstock: 13,
      brand: "nokia",
      img: "/img/apple.jpg",
      description: "costlyy phone",
    },
    {
      name: "Lenovo M Power",
      id: 5,
      rating: 4,
      nor: 10,
      noofstock: 18,
      price: 4010,
      brand: "lenovo",
      img: "/img/lenovo.jpg",
      description: "oota phone",
    },
    {
      name: "OnePlus Nord",
      id: 6,
      rating: 4.5,
      nor: 20,
      noofstock: 18,
      price: 34000,
      brand: "Oneplus",
      img: "/img/oneplus.jpg",
      description: "classy phone",
    },
    {
      name: "Vivo v10",
      id: 7,
      rating: 3.5,
      nor: 20,
      noofstock: 18,
      price: 14000,
      brand: "Vivo",
      img: "/img/vivo.jpg",
      description: "China phone",
    },
  ],
};
export default list;
