const list = {
  products: [
    {
      name: "nokia lumia",
      id: 1,
      rating: 4,
      nor: 10,
      price: 8000,
      brand: "nokia",
      img: "/img/nokia.jpg",
      description: "strong phone",
    },
    {
      name: "Sony xperia",
      id: 2,
      nor: 10,
      rating: 5,
      price: 15000,
      brand: "sony",
      img: "/img/sony.jpg",
      description: "camera phone",
    },
    {
      name: "samsung galaxy",
      id: 3,
      rating: 4,
      nor: 10,
      price: 10000,
      brand: "Samsung",
      img: "/img/samsung.jpg",
      description: "performace phone",
    },
    {
      name: "apple 11 pro",
      id: 4,
      rating: 4,
      nor: 10,
      price: 70000,
      brand: "nokia",
      img: "/img/apple.jpg",
      description: "costlyy phone",
    },
    {
      name: "lenovo m power",
      id: 5,
      rating: 4,
      nor: 10,
      price: 4000,
      brand: "lenovo",
      img: "/img/lenovo.jpg",
      description: "oota phone",
    },
  ],
};
export default list;
